version: '3.8'

# Production overrides for docker-compose.yml
services:
  app:
    environment:
      - ENV=production
      - MONGODB_URL=mongodb://mongo:27017/mergington_high_prod
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  mongo:
    environment:
      - MONGO_INITDB_DATABASE=mergington_high_prod
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'