name: Bug Report
description: Report something that isn't working correctly
title: "[Bug] "
labels: ["bug"]
assignees:
  - copilot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the details below so we can fix it.
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what you were trying to do and what went wrong
      placeholder: I was trying to... but instead...
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      description: What did you expect to happen instead?
      placeholder: I expected...
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can someone else see this problem?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true
  
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false
  
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Desktop/Laptop
        - Tablet
        - Phone
    validations:
      required: false
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Error Messages
      description: If you saw any error messages or can provide screenshots, please add them here
      placeholder: Paste screenshots or copy error messages here
    validations:
      required: false
  
  - type: dropdown
    id: severity
    attributes:
      label: How bad is this problem?
      description: How much does this affect your ability to use the website?
      options:
        - Minor - Small inconvenience
        - Moderate - Workaround exists
        - Major - Difficult to work around
        - Critical - Cannot use the website
    validations:
      required: true